version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  catalog.data:
    image: microsoft/mssql-server-linux:2017-latest
  catalog.api:
    # image: catalog-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Microservices/Catalog.Api/Dockerfile
    networks:
      - webnet
    ports:
      - "4001:80"
    depends_on:
      - catalog.data
      - rabbitmq
  
  basket.api:
    # image: catalog-api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Microservices/Basket.Api/Dockerfile
    networks:
      - webnet
    ports:
      - "4002:80"
    depends_on:
      - rabbitmq
      
networks:
  webnet:
    driver: bridge